[project]
name = "autogkb-benchmark"
description = "Benchmark for evaluating annotations"
version = "0.1.0"
channels = ["conda-forge", "pypi"]
platforms = ["osx-64", "linux-64"]

[dependencies]
python = ">=3.9"
requests = "*"
pandas = "*"
numpy = "*"

[tasks]
setup-repo = "pixi install && pixi run setup-data"
setup-data = "python -m src.data_setup.main"

[environments]
dev = { solve-group = "dev" }

[environments.dev.dependencies]
pytest = "*"
black = "*"
flake8 = "*"
mypy = "*"
